/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FileType = IDL.Variant({ 'PDF' : IDL.Null, 'Image' : IDL.Null });
export const AddDocumentPayload = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'fileType' : FileType,
  'category' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const Document = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'fileType' : FileType,
  'category' : IDL.Text,
  'docId' : IDL.Nat,
  'uploadDate' : Timestamp,
});
export const UserId = IDL.Principal;
export const UserProfilePublic = IDL.Record({
  'userId' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'email' : IDL.Text,
  'updatedAt' : Timestamp,
  'phone' : IDL.Text,
});
export const ServiceStatus = IDL.Variant({
  'NotLinked' : IDL.Null,
  'Verified' : IDL.Null,
  'Pending' : IDL.Null,
});
export const ServiceCategory = IDL.Variant({
  'Travel' : IDL.Null,
  'Identity' : IDL.Null,
  'FoodSecurity' : IDL.Null,
  'Finance' : IDL.Null,
  'Utilities' : IDL.Null,
});
export const GovServicePublic = IDL.Record({
  'status' : ServiceStatus,
  'metadata' : IDL.Text,
  'name' : IDL.Text,
  'lastUpdated' : Timestamp,
  'category' : ServiceCategory,
  'serviceId' : IDL.Text,
});
export const WebAuthnCredentialPublic = IDL.Record({
  'createdAt' : Timestamp,
  'credentialId' : IDL.Vec(IDL.Nat8),
  'deviceName' : IDL.Text,
});
export const UpdateProfilePayload = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const UpdateServicePayload = IDL.Record({
  'status' : ServiceStatus,
  'metadata' : IDL.Text,
  'serviceId' : IDL.Text,
});

export const idlService = IDL.Service({
  'addDocument' : IDL.Func([AddDocumentPayload], [IDL.Nat], []),
  'deleteDocument' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getUserDocuments' : IDL.Func([], [IDL.Vec(Document)], ['query']),
  'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfilePublic)], ['query']),
  'getUserServices' : IDL.Func([], [IDL.Vec(GovServicePublic)], ['query']),
  'getWebAuthnCredentials' : IDL.Func(
      [],
      [IDL.Vec(WebAuthnCredentialPublic)],
      ['query'],
    ),
  'initUserData' : IDL.Func([], [], []),
  'registerWebAuthnCredential' : IDL.Func(
      [IDL.Vec(IDL.Nat8), IDL.Vec(IDL.Nat8), IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'removeWebAuthnCredential' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'updateProfile' : IDL.Func([UpdateProfilePayload], [], []),
  'updateServiceStatus' : IDL.Func([UpdateServicePayload], [IDL.Bool], []),
  'verifyWebAuthnCredential' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FileType = IDL.Variant({ 'PDF' : IDL.Null, 'Image' : IDL.Null });
  const AddDocumentPayload = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'fileType' : FileType,
    'category' : IDL.Text,
  });
  const Timestamp = IDL.Int;
  const Document = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'fileType' : FileType,
    'category' : IDL.Text,
    'docId' : IDL.Nat,
    'uploadDate' : Timestamp,
  });
  const UserId = IDL.Principal;
  const UserProfilePublic = IDL.Record({
    'userId' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'email' : IDL.Text,
    'updatedAt' : Timestamp,
    'phone' : IDL.Text,
  });
  const ServiceStatus = IDL.Variant({
    'NotLinked' : IDL.Null,
    'Verified' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const ServiceCategory = IDL.Variant({
    'Travel' : IDL.Null,
    'Identity' : IDL.Null,
    'FoodSecurity' : IDL.Null,
    'Finance' : IDL.Null,
    'Utilities' : IDL.Null,
  });
  const GovServicePublic = IDL.Record({
    'status' : ServiceStatus,
    'metadata' : IDL.Text,
    'name' : IDL.Text,
    'lastUpdated' : Timestamp,
    'category' : ServiceCategory,
    'serviceId' : IDL.Text,
  });
  const WebAuthnCredentialPublic = IDL.Record({
    'createdAt' : Timestamp,
    'credentialId' : IDL.Vec(IDL.Nat8),
    'deviceName' : IDL.Text,
  });
  const UpdateProfilePayload = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UpdateServicePayload = IDL.Record({
    'status' : ServiceStatus,
    'metadata' : IDL.Text,
    'serviceId' : IDL.Text,
  });
  
  return IDL.Service({
    'addDocument' : IDL.Func([AddDocumentPayload], [IDL.Nat], []),
    'deleteDocument' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getUserDocuments' : IDL.Func([], [IDL.Vec(Document)], ['query']),
    'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfilePublic)], ['query']),
    'getUserServices' : IDL.Func([], [IDL.Vec(GovServicePublic)], ['query']),
    'getWebAuthnCredentials' : IDL.Func(
        [],
        [IDL.Vec(WebAuthnCredentialPublic)],
        ['query'],
      ),
    'initUserData' : IDL.Func([], [], []),
    'registerWebAuthnCredential' : IDL.Func(
        [IDL.Vec(IDL.Nat8), IDL.Vec(IDL.Nat8), IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'removeWebAuthnCredential' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'updateProfile' : IDL.Func([UpdateProfilePayload], [], []),
    'updateServiceStatus' : IDL.Func([UpdateServicePayload], [IDL.Bool], []),
    'verifyWebAuthnCredential' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };