/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddDocumentPayload {
  'title' : string,
  'description' : string,
  'fileType' : FileType,
  'category' : string,
}
export interface Document {
  'title' : string,
  'description' : string,
  'fileType' : FileType,
  'category' : string,
  'docId' : bigint,
  'uploadDate' : Timestamp,
}
export type FileType = { 'PDF' : null } |
  { 'Image' : null };
export interface GovServicePublic {
  'status' : ServiceStatus,
  'metadata' : string,
  'name' : string,
  'lastUpdated' : Timestamp,
  'category' : ServiceCategory,
  'serviceId' : string,
}
export type ServiceCategory = { 'Travel' : null } |
  { 'Identity' : null } |
  { 'FoodSecurity' : null } |
  { 'Finance' : null } |
  { 'Utilities' : null };
export type ServiceStatus = { 'NotLinked' : null } |
  { 'Verified' : null } |
  { 'Pending' : null };
export type Timestamp = bigint;
export interface UpdateProfilePayload {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export interface UpdateServicePayload {
  'status' : ServiceStatus,
  'metadata' : string,
  'serviceId' : string,
}
export type UserId = Principal;
export interface UserProfilePublic {
  'userId' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'email' : string,
  'updatedAt' : Timestamp,
  'phone' : string,
}
export interface WebAuthnCredentialPublic {
  'createdAt' : Timestamp,
  'credentialId' : Uint8Array,
  'deviceName' : string,
}
export interface _SERVICE {
  'addDocument' : ActorMethod<[AddDocumentPayload], bigint>,
  'deleteDocument' : ActorMethod<[bigint], boolean>,
  'getUserDocuments' : ActorMethod<[], Array<Document>>,
  'getUserProfile' : ActorMethod<[], [] | [UserProfilePublic]>,
  'getUserServices' : ActorMethod<[], Array<GovServicePublic>>,
  'getWebAuthnCredentials' : ActorMethod<[], Array<WebAuthnCredentialPublic>>,
  'initUserData' : ActorMethod<[], undefined>,
  'registerWebAuthnCredential' : ActorMethod<
    [Uint8Array, Uint8Array, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'removeWebAuthnCredential' : ActorMethod<
    [Uint8Array],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'updateProfile' : ActorMethod<[UpdateProfilePayload], undefined>,
  'updateServiceStatus' : ActorMethod<[UpdateServicePayload], boolean>,
  'verifyWebAuthnCredential' : ActorMethod<
    [Uint8Array],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];