/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type UserId = Principal;
export type Timestamp = bigint;
export interface AddDocumentPayload {
    title: string;
    description: string;
    fileType: FileType;
    category: string;
}
export interface UpdateProfilePayload {
    name: string;
    email: string;
    phone: string;
}
export interface UpdateServicePayload {
    status: ServiceStatus;
    metadata: string;
    serviceId: string;
}
export interface Document {
    title: string;
    description: string;
    fileType: FileType;
    category: string;
    docId: bigint;
    uploadDate: Timestamp;
}
export interface WebAuthnCredentialPublic {
    createdAt: Timestamp;
    credentialId: Uint8Array;
    deviceName: string;
}
export interface GovServicePublic {
    status: ServiceStatus;
    metadata: string;
    name: string;
    lastUpdated: Timestamp;
    category: ServiceCategory;
    serviceId: string;
}
export interface UserProfilePublic {
    userId: UserId;
    name: string;
    createdAt: Timestamp;
    email: string;
    updatedAt: Timestamp;
    phone: string;
}
export enum FileType {
    PDF = "PDF",
    Image = "Image"
}
export enum ServiceCategory {
    Travel = "Travel",
    Identity = "Identity",
    FoodSecurity = "FoodSecurity",
    Finance = "Finance",
    Utilities = "Utilities"
}
export enum ServiceStatus {
    NotLinked = "NotLinked",
    Verified = "Verified",
    Pending = "Pending"
}
export interface backendInterface {
    addDocument(payload: AddDocumentPayload): Promise<bigint>;
    deleteDocument(docId: bigint): Promise<boolean>;
    getUserDocuments(): Promise<Array<Document>>;
    getUserProfile(): Promise<UserProfilePublic | null>;
    getUserServices(): Promise<Array<GovServicePublic>>;
    getWebAuthnCredentials(): Promise<Array<WebAuthnCredentialPublic>>;
    initUserData(): Promise<void>;
    registerWebAuthnCredential(credentialId: Uint8Array, publicKey: Uint8Array, deviceName: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    removeWebAuthnCredential(credentialId: Uint8Array): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateProfile(payload: UpdateProfilePayload): Promise<void>;
    updateServiceStatus(payload: UpdateServicePayload): Promise<boolean>;
    verifyWebAuthnCredential(credentialId: Uint8Array): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { AddDocumentPayload as _AddDocumentPayload, Document as _Document, FileType as _FileType, GovServicePublic as _GovServicePublic, ServiceCategory as _ServiceCategory, ServiceStatus as _ServiceStatus, Timestamp as _Timestamp, UpdateServicePayload as _UpdateServicePayload, UserProfilePublic as _UserProfilePublic } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addDocument(arg0: AddDocumentPayload): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addDocument(to_candid_AddDocumentPayload_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDocument(to_candid_AddDocumentPayload_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteDocument(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDocument(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDocument(arg0);
            return result;
        }
    }
    async getUserDocuments(): Promise<Array<Document>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserDocuments();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserDocuments();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserServices(): Promise<Array<GovServicePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserServices();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserServices();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWebAuthnCredentials(): Promise<Array<WebAuthnCredentialPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWebAuthnCredentials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWebAuthnCredentials();
            return result;
        }
    }
    async initUserData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initUserData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initUserData();
            return result;
        }
    }
    async registerWebAuthnCredential(arg0: Uint8Array, arg1: Uint8Array, arg2: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.registerWebAuthnCredential(arg0, arg1, arg2);
                return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerWebAuthnCredential(arg0, arg1, arg2);
            return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeWebAuthnCredential(arg0: Uint8Array): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.removeWebAuthnCredential(arg0);
                return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeWebAuthnCredential(arg0);
            return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProfile(arg0: UpdateProfilePayload): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0);
            return result;
        }
    }
    async updateServiceStatus(arg0: UpdateServicePayload): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateServiceStatus(to_candid_UpdateServicePayload_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateServiceStatus(to_candid_UpdateServicePayload_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async verifyWebAuthnCredential(arg0: Uint8Array): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyWebAuthnCredential(arg0);
                return from_candid_variant_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyWebAuthnCredential(arg0);
            return from_candid_variant_n23(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Document_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Document): Document {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_FileType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FileType): FileType {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_GovServicePublic_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GovServicePublic): GovServicePublic {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceCategory_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceCategory): ServiceCategory {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceStatus): ServiceStatus {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfilePublic]): UserProfilePublic | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ServiceStatus;
    metadata: string;
    name: string;
    lastUpdated: _Timestamp;
    category: _ServiceCategory;
    serviceId: string;
}): {
    status: ServiceStatus;
    metadata: string;
    name: string;
    lastUpdated: Timestamp;
    category: ServiceCategory;
    serviceId: string;
} {
    return {
        status: from_candid_ServiceStatus_n14(_uploadFile, _downloadFile, value.status),
        metadata: value.metadata,
        name: value.name,
        lastUpdated: value.lastUpdated,
        category: from_candid_ServiceCategory_n16(_uploadFile, _downloadFile, value.category),
        serviceId: value.serviceId
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    description: string;
    fileType: _FileType;
    category: string;
    docId: bigint;
    uploadDate: _Timestamp;
}): {
    title: string;
    description: string;
    fileType: FileType;
    category: string;
    docId: bigint;
    uploadDate: Timestamp;
} {
    return {
        title: value.title,
        description: value.description,
        fileType: from_candid_FileType_n8(_uploadFile, _downloadFile, value.fileType),
        category: value.category,
        docId: value.docId,
        uploadDate: value.uploadDate
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    NotLinked: null;
} | {
    Verified: null;
} | {
    Pending: null;
}): ServiceStatus {
    return "NotLinked" in value ? ServiceStatus.NotLinked : "Verified" in value ? ServiceStatus.Verified : "Pending" in value ? ServiceStatus.Pending : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Travel: null;
} | {
    Identity: null;
} | {
    FoodSecurity: null;
} | {
    Finance: null;
} | {
    Utilities: null;
}): ServiceCategory {
    return "Travel" in value ? ServiceCategory.Travel : "Identity" in value ? ServiceCategory.Identity : "FoodSecurity" in value ? ServiceCategory.FoodSecurity : "Finance" in value ? ServiceCategory.Finance : "Utilities" in value ? ServiceCategory.Utilities : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: boolean;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    PDF: null;
} | {
    Image: null;
}): FileType {
    return "PDF" in value ? FileType.PDF : "Image" in value ? FileType.Image : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GovServicePublic>): Array<GovServicePublic> {
    return value.map((x)=>from_candid_GovServicePublic_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Document>): Array<Document> {
    return value.map((x)=>from_candid_Document_n6(_uploadFile, _downloadFile, x));
}
function to_candid_AddDocumentPayload_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AddDocumentPayload): _AddDocumentPayload {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_FileType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FileType): _FileType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_ServiceStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceStatus): _ServiceStatus {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateServicePayload_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateServicePayload): _UpdateServicePayload {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    description: string;
    fileType: FileType;
    category: string;
}): {
    title: string;
    description: string;
    fileType: _FileType;
    category: string;
} {
    return {
        title: value.title,
        description: value.description,
        fileType: to_candid_FileType_n3(_uploadFile, _downloadFile, value.fileType),
        category: value.category
    };
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: ServiceStatus;
    metadata: string;
    serviceId: string;
}): {
    status: _ServiceStatus;
    metadata: string;
    serviceId: string;
} {
    return {
        status: to_candid_ServiceStatus_n21(_uploadFile, _downloadFile, value.status),
        metadata: value.metadata,
        serviceId: value.serviceId
    };
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceStatus): {
    NotLinked: null;
} | {
    Verified: null;
} | {
    Pending: null;
} {
    return value == ServiceStatus.NotLinked ? {
        NotLinked: null
    } : value == ServiceStatus.Verified ? {
        Verified: null
    } : value == ServiceStatus.Pending ? {
        Pending: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FileType): {
    PDF: null;
} | {
    Image: null;
} {
    return value == FileType.PDF ? {
        PDF: null
    } : value == FileType.Image ? {
        Image: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
